ec2 image validation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -44,19 +44,24 @@ commands:
   ec2_image_verify:
     steps:
       - run: |
-          yum install -y epel-release
-          yum install -y jq
-      - run: |
           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
           unzip awscliv2.zip
           sudo ./aws/install
       - run: |
           aws configure set default.region us-east-1
-          aws configure set aws_access_key_id echo $(echo $aws_access_key_id | base64 -d -w 0)
-          aws configure set aws_secret_access_key echo $(echo $aws_secret_access_key | base64 -d -w 0)
+          aws configure set aws_access_key_id $(echo $aws_access_key_id | base64 -d -w 0)
+          aws configure set aws_secret_access_key $(echo $aws_secret_access_key | base64 -d -w 0)
           aws configure set output json
-          aws ecr get-login | sudo sh
-      - run: aws ec2 describe-images --filters Name=name,Values=CentOS7-cloudify-examples-image | jq -r '.[]'
+      - run: |
+          ret=`aws ec2 describe-images --filters Name=name,Values=CentOS7-cloudify-examples-image | jq '.Images' | jq -r '.[0].Name'`
+          if [ $ret != "CentOS7-cloudify-examples-image" ]; then
+              echo "The current AWS account cannot find the required examples image. Tests cannot pass.";
+              exit 1;
+          else
+              echo "Found it!";
+              exit 0;
+          fi
+
 
   eks_prepare_test_manager:
     steps:
@@ -156,16 +161,10 @@ commands:
 jobs:
 
   verify_ec2_image:
-    executor: circleci/python:3.6
+    executor: py36
     steps:
+      - checkout
       - ec2_image_verify
-
-  run_sample_job:
-    executor: cloudify-machine-py3
-    environment:
-      CLOUDIFY_SSL_TRUST_ALL: true
-    steps:
-      - run_sample_test
 
   cf_integration_tests_py3:
     executor: cloudify-machine-py3
@@ -406,7 +405,6 @@ workflows:
               only: /([0-9\.]*\-build|master|dev)/
       - eks_integration_tests_py3:
           requires:
-            - verify_ec2_image
             - wagonorb/wagon
             - wagonorb/rhel_wagon
             - wagonorb/arch64_wagon
@@ -415,7 +413,6 @@ workflows:
               only: /([0-9\.]*\-build|master|dev)/
       - hw_integration_tests_py3:
           requires:
-            - verify_ec2_image
             - wagonorb/wagon
             - wagonorb/rhel_wagon
             - wagonorb/arch64_wagon
@@ -455,6 +452,7 @@ workflows:
             only:
               - master
     jobs:
+      - verify_ec2_image
       - node/check_py3_compat_job
       - node/unittests_job:
           context: 
@@ -489,6 +487,7 @@ workflows:
             - slack-secrets
           <<: *job-post-steps
           requires:
+            - verify_ec2_image
             - wagonorb/wagon
             - wagonorb/rhel_wagon
             - wagonorb/arch64_wagon
@@ -500,6 +499,7 @@ workflows:
             - slack-secrets
           <<: *job-post-steps
           requires:
+            - verify_ec2_image
             - wagonorb/wagon
             - wagonorb/rhel_wagon
             - wagonorb/arch64_wagon
@@ -540,6 +540,7 @@ workflows:
             only:
               - master
     jobs:
+      - verify_ec2_image
       - node/check_py3_compat_job
       - node/unittests_job:
           context: 
@@ -574,6 +575,7 @@ workflows:
             - slack-secrets
           <<: *job-post-steps
           requires:
+            - verify_ec2_image
             - wagonorb/wagon
             - wagonorb/rhel_wagon
             - wagonorb/arch64_wagon
@@ -635,6 +637,7 @@ workflows:
             only:
               - master
     jobs:
+      - verify_ec2_image
       - node/check_py3_compat_job
       - node/unittests_job:
           context: 
@@ -658,6 +661,7 @@ workflows:
             - slack-secrets
           <<: *job-post-steps
           requires:
+            - verify_ec2_image
             - wagonorb/wagon
             - wagonorb/rhel_wagon
             - wagonorb/arch64_wagon
